[project]
name = "orm-note"
version = "0.1.0"
description = ""
authors = [
    { name = "uuip", email = "uuip@users.noreply.github.com" }
]
readme = "README.md"
requires-python = ">=3.14,<4"
dependencies = [
    "sqlalchemy[asyncio] >=2.1.2",
    "pydantic >=2.13.5",
    "pydantic-settings >=2.15.0",
    "psycopg[binary,pool] >=3.3.6",
    "pymysql >=1.2.3",
    "cryptography >=50.0.2",
    "pwdlib[argon2]>=0.3.1",
    "pypika>=0.51.1",
]

[tool.uv]
package = false

[tool.ruff.lint]
ignore = [
    "F405",
    "F403",
]
